#!/bin/bash

if [ -n "$(uname -a | grep -i ^linux)" ] ; then
    HERE="$(dirname $(readlink -f $0))"
else
    HERE="$(dirname $0)"
fi

export ASPEN_GO_CONFIGURATION_SCRIPTS="${ASPEN_GO_CONFIGURATION_SCRIPTS:-"$HERE/web-config.go"}"
export DEBUG="${DEBUG:-1}"
export GOPATH="$HERE:$GOPATH"

exec aspen-go-build \
    -w "$HERE/docroot" \
    -P aspen_go_smoke_test \
    --indices +default.htm \
    --list_directories "$@"
